---
title: Xiao Zhang
tagline: A Philosophy Blog
description:


author:
name:
url: 
github_username:  xxz619
 
paginate: 5
exclude:
- README.md
- vendor/bundle
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: false
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''


# Build settings
theme: jekyll-theme-hydeout
